### ISSUE TITLE
quart-trio is not compabtible with quart 0.19.0 and above

### ISSUE THREAD

**Issue by vxgmichel** [pgjones/quart-trio#11]
The method `Quart.try_trigger_before_first_request_functions` no longer exists:

```python
Traceback (most recent call last):
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.9/site-packages/quart_trio/app.py", line 183, in handle_websocket
    return await self.full_dispatch_websocket(websocket_context)
  File "/home/vinmic/miniconda/envs/parsec/lib/python3.9/site-packages/quart_trio/app.py", line 204, in full_dispatch_websocket
    await self.try_trigger_before_first_request_functions()
AttributeError: 'BackendQuartTrio' object has no attribute 'try_trigger_before_first_request_functions'
```

It has been removed in this commit:
https://github.com/pallets/quart/commit/598b771abd36fb2d581aa88a64336c88615a26bf

**Comment by pgjones** [comment]
Fixed in 4c59acfb5f7dc8782498424aec27f6a25fdd7cee
